### ISSUE TITLE
Questions on Unified Time Series Dataset and Model Training Resources

### ISSUE THREAD

**Issue by wyl010607** [thuml/Large-Time-Series-Model#1]
Hello,

I'm truly impressed by your recent work on using pure decoder-based Transformer architectures for time series tasks. It’s great to see such innovative approaches being explored.

I have a couple of questions I’m hoping you could help with:

1. Dataset Availability: You've mentioned the "Unified Time Series Dataset" in your research. Are there plans to make this dataset publicly available? If so, how and when can it be accessed?
2. Resource Utilization for Model Training: You’ve discussed models of different sizes like 3M, 29M, and 51M parameters. Could you share details about the computational resources required for training these models? Specifically:
    What GPU resources were used?
    How long did the training take for each model size?
Thanks for sharing your findings and I look forward to your response!

Best,

**Comment by WenWeiTHU** [comment]
Thank you for your attention.
* We are working on a HuggingFace version of UTSD. It is expected that data sets of various sizes will be opened up to support the study of LTSMs scalability.
* The resource utilization is included in the appendix. We are currently working on a camera ready version that will include more detailed instructions. Please stay tuned!
