### ISSUE TITLE
How to pretrain a Timer model?

### ISSUE THREAD

**Issue by lukc12138** [thuml/Large-Time-Series-Model#12]
Thanks for the great work. I'm currently working on pretraining, I wonder if there is a way to pretrain a timer model. Is the pretraining code available?

**Comment by aichicaideyang** [comment]
Have you already solved this problem？ I‘m also curious about this right now...

**Comment by WenWeiTHU** [comment]
Hi, we plan to open source the pre-training code (along with the implementation of other large time series mode and large-scale data loading logic). Please stay tuned!

**Comment by WenWeiTHU** [comment]
Done!
