### ISSUE TITLE
How to custom own dataset

### ISSUE THREAD

**Issue by Sample-design-alt** [thuml/Large-Time-Series-Model#13]
Thanks for you great work! 
But how should I custom my own dataset in the pretraining stage?

**Comment by WenWeiTHU** [comment]
Of course, we plan to open source the large-scale data loading logic. Please stay tuned!

**Comment by WenWeiTHU** [comment]
We have provided the scripts for pre-training in [this repo](https://github.com/thuml/OpenLTM/blob/main/scripts/pretrain/timer_xl_utsd.sh)!
