### ISSUE TITLE
Zero-shot forcasting

### ISSUE THREAD

**Issue by zhajiahe** [thuml/Large-Time-Series-Model#15]
Could you provide a script for reproducing the zero-shot forcasting results?

**Comment by WenWeiTHU** [comment]
Hi, we are going to open source the zero-shot benchmark (along with some other large model structures and large-scale data loading logic). Please stay tuned!

**Comment by WenWeiTHU** [comment]
We have provided the scripts for zero-shot evaluation in [this repo](https://github.com/thuml/OpenLTM/blob/main/scripts/adaptation/zero_shot/timer_xl_etth1.sh)!
