### ISSUE TITLE
Regarding the pre-training weight parameters.

### ISSUE THREAD

**Issue by ooooooover** [thuml/Large-Time-Series-Model#16]
Thank you for your excellent work, so far you have shared the checkpoints for Timer-28B which is the version with 67M parameters, could you please share the checkpoints for Timer-1B and Timer-16B?

**Comment by WenWeiTHU** [comment]
Of course! The [checkpoint](https://drive.google.com/drive/folders/15oaiAl4OO5gFqZMJD2lOtX2fxHbpgcU8?usp=drive_link) in the current repo is the 1B-version pre-trained on UTSD-12G. We are going to release the larger one (and with more advanced model architecture) in near future.
