### ISSUE TITLE
关于single-series sequence(S3)的疑问

### ISSUE THREAD

**Issue by mike-egg123** [thuml/Large-Time-Series-Model#21]
在处理多变量的时间序列时，每个变量对应的序列做了归一化之后，是如何进行merge变成single-variate series的呢？是进行首尾拼接吗？我看附的图是首尾拼接的意思，但如果是首尾拼接的话，这样是否太简单粗暴了呀？如果不是的话，能否将merge的方法告知于我？我看论文中并没有展开论述。
![image](https://github.com/user-attachments/assets/b8e813d9-0533-40e0-b4d9-83c4fe637516)

**Comment by WenWeiTHU** [comment]
您好，并非首尾拼接，而是放在一个内存池中，切窗口的时候不会出现一个窗口中包括两个不同序列的情况，数据加载逻辑请参考：https://github.com/thuml/OpenLTM/blob/main/data_provider/data_loader.py#L505
