### ISSUE TITLE
If I have time points less than 672 with only 580, is that possbile to predict with Timer?

### ISSUE THREAD

**Issue by gjfdklfjd** [thuml/Large-Time-Series-Model#22]

**Comment by WenWeiTHU** [comment]
Of course. For inputs less than context length(672), decoder-only Timer can make predictions, but you may need to pad the input as a multiple of token length(96).

**Comment by aheq123** [comment]
z请问下，为什么input从672换成192就不行了，label len还是576，然后我试了下把label_len 换成92，这样我的input=192，label=96，模型才能跑起来，如果是input=192，label=192，模型是没办法运行的，这是为什么？就像你input=672，label=576才能运行，都等于672是不能运行的，为什么呢
