### ISSUE TITLE
Decoder-only or Encoder-only

### ISSUE THREAD

**Issue by ZChaowen** [thuml/Large-Time-Series-Model#23]
我看论文中写的是Decoder-only但是开源的代码里面用的是Encoder的结构
![image](https://github.com/user-attachments/assets/e73a7d9f-b70c-4d02-9519-57d1a1c55cc7)

**Comment by WenWeiTHU** [comment]
Sorry for the misunderstanding of the name here, in fact, ```Encoder``` here refers to transformer block, so the Decoder-only mentioned in the paper in fact contains two meanings: (1) **causal masked attention** (```mask=True``` when initialize ```FullAttention```) (2) **token-wise embedding and projection**.

**Comment by WenWeiTHU** [comment]
To be compatible with checkpoints already in the repository, we added a comment here in the commit: https://github.com/thuml/Large-Time-Series-Model/commit/4ff2bc2ac81e7360c845c8e3c076a24022209631
