### ISSUE TITLE
A bug in run.py

### ISSUE THREAD

**Issue by TobyYang7** [thuml/Large-Time-Series-Model#3]
At line12 in `run.py`
```python
from exp.exp_imputation import Exp_Imputation
```

it should be changed to 
```python
from exp.exp_imputation import Exp_Imputation
```

**Comment by WenWeiTHU** [comment]
Thanks for your reminder! Do you mean the file name? We fix it in 08c098700ebd2f49e995fdce5e6ee4235c739daa.

**Comment by TobyYang7** [comment]
Thanks for your response. I made a mistake earlier; it should be
```python
from exp.exp_large_forecast import Exp_Forecast
```
btw, I really like the work your team is doing. I'm currently learning it as well.

**Comment by WenWeiTHU** [comment]
Thanks again for your help. Feel free to raise any questions!
