### ISSUE TITLE
Could you please provide a beginner's guide or tutorial document?

### ISSUE THREAD

**Issue by Louaq** [thuml/Large-Time-Series-Model#34]

**Comment by WenWeiTHU** [comment]
Hi, we have released a large version of Timer on [HuggingFace](https://huggingface.co/thuml/timer-base-84m). A notebook example is also provided [here](https://huggingface.co/thuml/timer-1.1-84m/blob/main/prediction_example_etth1.ipynb). Try it out!

**Comment by Louaq** [comment]
Thank you for the reply.
