### ISSUE TITLE
Does the data's sampling interval affect the prediction?

### ISSUE THREAD

**Issue by ANopony** [thuml/Large-Time-Series-Model#37]
Hi,
I have used a variety of datasets to perform forecast task, including microsecond data sets and second data sets, from which I found that the model doesn‘t perform well on microsecond data sets.
![Uploading image.png…]()

And MOIRAI saids it does affect. That's why I submit this issue.
Thanks for you patient reply.

**Comment by WenWeiTHU** [comment]
Hi, that is a really essential challenge and future direction for large time-series models! As UTSD generally emcompasses hourly to daily sampled time series, the performance on microsecond data is not guaranteed. 

Fortunately, we have released a new version of Timer on [HuggingFace](https://huggingface.co/thuml/timer-base-84m) with more high-freq data. A notebook example is provided [here](https://github.com/thuml/Large-Time-Series-Model/blob/main/examples/quickstart_zero_shot.ipynb). If you are interested, please try it out.

**Comment by ANopony** [comment]
I got that. Thanks for your reply!
