### ISSUE TITLE
方便通过 Tsinghua Cloud 分享一下UTSD数据集吗？

### ISSUE THREAD

**Issue by dawnvince** [thuml/Large-Time-Series-Model#5]
感谢开源数据集和checkpoint，timer对时序领域scaling的探究是一项非常有价值的工作。

我尝试从hf-mirror上拉thuml/UTSD数据集，但在fetching第277个文件时总会报错 “416 Client Error: Range Not Satisfiable for url”。方便的话可以通过 Tsinghua Cloud 分享一下整个UTSD数据集吗？

**Comment by WenWeiTHU** [comment]
您好，我们加入了UTSD的[数据下载代码](https://github.com/thuml/Large-Time-Series-Model/tree/main/scripts/UTSD)，遇到网络问题可以尝试多拉取几次，如果还有问题请和我们反馈。

**Comment by dawnvince** [comment]
使用下载代码时依然报错 OSError: Consistency check failed: file should be of size 12861488 but has size 12861552 ((…)f4d9eb/UTSD-4G/data-00029-of-00080.arrow). 在下载前已经清除了huggingface的cache，同样报错。。

在另一台设备和新的网络环境下使用git clone会出现同样的错误 :(
