### ISSUE TITLE
Zero-shot forecasting without training

### ISSUE THREAD

**Issue by ozanbarism** [thuml/Large-Time-Series-Model#6]
Hi, is there a way for me to do zero-shot forecasting with timer without training it?

**Comment by WenWeiTHU** [comment]
Of course, you can load the pre-trained model as you would with any other large time series model and directly input a time series for prediction (currently Timer supports no longer than 1440 sequence lengths).  For longer sequence outputs, you can try using the autoregression provided in our code.

**Comment by flightttt** [comment]
> Of course, you can load the pre-trained model as you would with any other large time series model and directly input a time series for prediction (currently Timer supports no longer than 1440 sequence lengths). For longer sequence outputs, you can try using the autoregression provided in our code.

Hello, thanks for your patience. You mentioned "using the autoregression provided in our code" but I couldn't find this part in the code repository. Did I misunderstand or was it not uploaded?
